- name: Install Pandas
  hosts: all
  tasks:
    - name: Install pandas
      command: python3 -m pip install pandas
      register: out
    - debug: var=out.stdout

    - name: Generate config file primary
      command: touch /tmp/test_primary.txt
      when: inventory_hostname in groups.primary # "'primary' in group_names" "'secondary' in group_names"
      register: out  
    - debug: var=out.stdout

    - name: Generate config file secondary
      command: ls /root/ -l
      register: out  
    - debug: var=out.stdout
