- name: Install Pandas
  hosts: all
  become: yes
  tasks:
    - name: Install pandas
      command: python3 -m pip install pandas
      register: out
    - debug: var=out.stdout

    - name: Generate config file primary
      command: touch /tmp/test_primary.txt
      register: out  
    - debug: var=out.stdout

    - name: Generate config file secondary
      command: ls /root/ -l
      register: out  
    - debug: var=out.stdout

    - name: Exibir o valor de meu_parametro
      debug:
        msg: "O valor de meu_parametro é {{ my_parameter }}"