- name: Install Pandas
  hosts: all
  become: yes
  tasks:
    - name: Install pandas
      command: python3 -m pip install pandas
      register: out
    - debug: var=out.stdout

    - name: Generate config file primary
      copy:
        content: "{{ content_file }}"
        dest: "/tmp/test_primary.txt"
      when: generate_file == 1
      register: out  
    - debug: var=out.stdout

    - name: List tmp dir
      command: ls /tmp/
      register: out  
    - debug: var=out.stdout

    - name: Show the value of content_file 
      debug:
        msg: "O valor content_file é {{ content_file }}"
